kind: pipeline
type: docker
name: CI
 
 
trigger:
  event:
    - push


steps:
  - name: build
    - image: docker:latest
    - services:
        - docker:dind
    - commands:
        - docker build --pull -t  .
        - docker push 
