kind: pipeline
type: docker
name: CI
 
 
trigger:
  event:
    - push

steps:
  - name: build-docker-image
    image: plugins/docker
    settings:
        dockerfile: portfolio/Dockerfile
        context: portfolio/
        registry: hub.codefirst.iut.uca.fr
        repo: hub.codefirst.iut.uca.fr/noan.randon/portfolio_nrn
        username:
          from_secret: SECRET_REGISTRY_USERNAME
        password:
          from_secret: SECRET_REGISTRY_PASSWORD